### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by justin-qingshan** [typora/typora-ash-theme#1]
When using this theme, and I can hardly see anything in "preference page" of typora.

**Comment by jc776** [comment]
Example (Windows, Unibody)
![image](https://user-images.githubusercontent.com/6420993/30780883-3b4fc1c6-a10d-11e7-8387-adf660fbac83.png)

The system-native preferences page is OK.
![image](https://user-images.githubusercontent.com/6420993/30780905-7447b9f2-a10d-11e7-98f7-147008dfb12b.png)
