### ISSUE TITLE
Theme is brighter that screenshots and code block has no background

### ISSUE THREAD

**Issue by cryodream** [typora/typora-ash-theme#4]
I just installed Typora for the first time an hour ago and was checking it out. I very much prefer **dark** themes, but I did not like the single default dark theme - **Night**. I went to look for something better at [Themes Gallery — Typora](https://theme.typora.io/) asd found your theme. I liked it straight away - the screenshots, that is...

I downloaded and installed it, as per instructions. But I have 2 problems straight away:

1. The theme has quite brighter tone (the background), than in your screenshots.
2. The code block has no darker background at all. That makes the code blocks look, well... messy and confusing.

Please take a look at the screenshot.  
On the right side - your original screenshot from here: [Ash](https://theme.typora.io/theme/Ash/)
On the left - my Typora with your theme enabled.

![2018-09-27_04-17-58__typora](https://user-images.githubusercontent.com/844036/46133404-6125d480-c20e-11e8-8e79-ec5078d84a31.png)

Frankly, with so little dark theme choices, and speaking only only for myself and my own taste in colors - Ash is the only really usable dark theme, which is easy on the eyes.

Please, help me fix these issues.
Thanks in advance for any help.

**Comment by abnerlee** [comment]
What's your OS?

**Comment by cryodream** [comment]
@abnerlee Windows 10

**Comment by RJSackville** [comment]
I have met the same problem. I tried on Windows10-1803 and MacOS-10.14. The code blocks do not have its own background. Sometimes it's hard to distinguish the code blocks and normal paragraphs.

**Comment by abnerlee** [comment]
@cryodream @RJSackville What's your Typora version?

**Comment by RJSackville** [comment]
> 
> 
> @cryodream @RJSackville What's your Typora version?

version 0.9.58(beta) on Windows10
version 0.9.9.18.1(1088) on MacOS

**Comment by cryodream** [comment]
Same here:
version 0.9.58(beta) on Windows10

**Comment by abnerlee** [comment]
fixed in https://github.com/typora/typora-ash-theme/commit/c4239ed552625e06aedf0a6223f6da8a4b5527fd

Please re-download the ash theme
