### ISSUE TITLE
Feature request? - Adjustable margins?

### ISSUE THREAD

**Issue by Leron4551** [typora/typora-ash-theme#6]
I have spent the past two days looking for a note taking app for Mac that I like. I found Typora and it has the features I wanted but the aesthetics were a bit off for my taste. Then I found the Ash theme ,and I ADORE this theme. It's everything I was looking for. My only quibble is that the margins are a bit large for my preference. Would it be possible to incorporate a section of the CSS file for adjusting this? The checkmarks are a bit too large and have a large space on either side of them, If I could reduce those margins I'd be very happy. Is there any likelihood of entertaining this request?

**Comment by abnerlee** [comment]
You can refer https://support.typora.io/Add-Custom-CSS/
